### ISSUE TITLE
Future features

### ISSUE THREAD

**Issue by felipevolpone** [shnode/PyTime#1]
Hey @shnode, do you have some plans of future features? I would like to help the project.

**Comment by shinux** [comment]
Hola @felipevolpone ，thanks for your taking notice of this repo. I'm considering to do something like converting `Apr.1st,1985` to `datetime.datetime(1985, 8, 1)` , and Refactoring code.Actually the existing code is not clean enough.

**Comment by felipevolpone** [comment]
Nice! I could do it, what do you think?

**Comment by shinux** [comment]
@felipevolpone Just do it, buddy!

**Comment by blade254353074** [comment]
Het @shnode , are you handsome?
