### ISSUE TITLE
Confusion about month abbreviations

### ISSUE THREAD

**Issue by weiqingcai** [shnode/PyTime#10]
Thank you very much for checking my issue. I found that August was abbreviated as Agu instead of Aug when I used it, which made me very confused. I want to ask why this is?
example found in filter.py file：
NAMED_MONTHS = {'Jan': 1, 'Feb': 2, 'Mar': 3, 'Apr': 4,
                'May': 5, 'Jun': 6, 'Jul': 7, 'Agu': 8,
                'Sep': 9, 'Oct': 10, 'Nov': 11, 'Dec': 12}

**Comment by shinux** [comment]
Sorry, just a typo and fixed in #11 

Please check  and upgrade to  `v0.2.2`: https://pypi.org/project/pytime/
