### ISSUE TITLE
Want to add improvements and fix some errors

### ISSUE THREAD

**Issue by dinkopehar** [shnode/PyTime#6]
Hi @shinux . 
First of all, very nice module. Lot of handy methods to use for date and time manipulation.
I know last commit was years ago, but I would like to fix some things because I find this module useful and really easy to read. Also, it would be my first contribution to open source.

Here is what I found digging through PyTime, first some minor mistakes:

1. At the end of `filter.py`, in method `from_str`, there is typo at last line, `raise CanNotFormatError('Not well formated. Expecting something like May,21st.2015')`. _formated_ should be **formatted**
2. At the end of `filter.py`, at `if __name__ == '__main__':`, there is PEP 8 violation. `PEP 8: expected 2 blank lines after class or function definition, found 1`. Missing one more blank line
3. In function daysrange, parameter `wipe` is not documented.

Now second list may or may not be problems, you decide.
1. In `test_normal.py`, in method `test_function`, `this7` and `this8` fail. On my machine, I setup this so it can show test as your tested, +2h offset I guess. I think you wanted to get from `pytime.yesterday(1432310400 + gmt8offset)` -> `datetime.datetime(2015, 5, 22, 0, 0)`. And you get it, but you are comparing  it to `datetime.datetime(2015, 5, 22)` which returns false, because tuple comparison fails here. Similiar is for `this8`.
2. Maybe better aproach would be to rename `daysrange` to `days_range`, `newyear` to `new_year`, `christeve` to `christ_eve` and `lastday` to `last_day`. That is because words should be split with underscore by conventions of python using snake case, and you already use that convention for `this_week`, `last_week`, `next_month` and so on.
3. In `filter.py`, in method `__parse_not_only_str`, `function` word usage in for loop is too broad term to be used. Maybe rename it to `baseParser_function`. Found some problems with pycharm too. [link here](https://stackoverflow.com/questions/45214672/shadows-built-in-names-function-and-module-with-pycharm)

There are some other things, but I would like to change some of those mentioned above if you would allow me to make pull request.
Thank you for your time.

**Comment by dinkopehar** [comment]
Fixed everything, just not sure about 1. in second list. I think you wanted to get output datetime.datetime(2015, 5, 22), but pytime.yesterday(1432310400 + gmt8offset) returns it with hour and minute in my case.

**Comment by shinux** [comment]
Hi @PinkFrojd .
I'm gonna say you did good code review, especially for the `IDE friendly` part. 
Any pull request will be welcome. :smiley:

**Comment by shinux** [comment]
> Fixed everything, just not sure about 1. in second list. I think you wanted to get output datetime.datetime(2015, 5, 22), but pytime.yesterday(1432310400 + gmt8offset) returns it with hour and minute in my case.

Some test cases depended on the test running moment.

**Comment by dinkopehar** [comment]
Can you please review what I have done? Thank you for being friendly 😄

**Comment by dinkopehar** [comment]
I see TravisCI failed 😢 . I think it's about tests I changed. I will change back to original those tests.

EDIT:

Sorry to bother you, but I checked TravisCI, and it fails only on python 2.6 running [`pip install coveralls`](https://travis-ci.org/shinux/PyTime/jobs/452734821#L565). But I checked coveralls module, and it doesn't support python 2.6 anymore. I know this is older project, but I'm just trying make contributions.

**Comment by shinux** [comment]
> I see TravisCI failed 😢 . I think it's about tests I changed. I will change back to original those tests.
> 
> EDIT:
> 
> Sorry to bother you, but I checked TravisCI, and it fails only on python 2.6 running [`pip install coveralls`](https://travis-ci.org/shinux/PyTime/jobs/452734821#L565). But I checked coveralls module, and it doesn't support python 2.6 anymore. I know this is older project, but I'm just trying make contributions.

Maybe you can edit  `.travis.yml` and remove supports for Python 2.6, and make some changes on README.md or something else to get this pr merged.

**Comment by dinkopehar** [comment]
Ok. I will try to do that. Thank you

**Comment by dinkopehar** [comment]
Thanks for being kind to me. I'm still beginner. I removed python 2.6, from `.travis.yml` and from `setup.py`. All tests and checks have been passed. You can see pull request again #7
